local gop = require "utils.gop"

function init(self)
	gop = gop.get_properties()
end

function update(self, dt)
    local pos = go.get_position()
    if pos.x < 0 then 
    	pos.x = 0 
    	gop.direction.x = -gop.direction.x
    elseif pos.x > 800 then
    	pos.x = 800
    	gop.direction.x = -gop.direction.x
    end
    if pos.y < 0 then 
    	pos.y = 0 
    	gop.direction.y = -gop.direction.y
    elseif pos.y > 600 then
    	pos.y = 600
    	gop.direction.y = -gop.direction.y
    end
    
end