local level = require "level.level_1"
local level_width = 9
local level_height = 5
local offset_x = 220
local offset_y = 470


function init(self)
    for i = 1, level_height do
    	for j = 1 , level_width do
    		if level[i][j] > 0 then
    			local pos = vmath.vector3(j*40+ offset_x,(level_height - i+1)*19+offset_y,0)
    			factory.create("/factories#bricks",pos,nil,{ life = level[i][j] })
    		end
    	end
    end
end